non_query_words_list = [
                        "thank you", "thanks", "bye", "goodbye", "hello", "hi", "hey", "see you later", 
                        "how are you", "sorry", "excuse me","thank you so much","thank you", "thanks", "bye", 
                        "goodbye", "hello", "hi", "hey", "see you later", "how are you", "sorry", "excuse me",
                        "thank you so much", "ok", "okay", "sure", "no problem", "great", "awesome", "cool", "thank"
                        "thanks a lot", "cheers", "take care", "you're welcome", "appreciate it",  "thanks for your help"
                        ]
    
    
abusive_words_list = [
                      r"\bchutiyapa\b", r"\bgandmasti\b", r"\bchutiyagiri\b", r"\bmuhnochwa\b", r"\bthirudargal\b",
                      r"\bthirudargalgal\b", r"\bgandu\b", r"\bthirudan\b", r"\btholla\b", r"\bthirudargalgal\b",
                      r"\bthirudargal\b", r"\btanglish\b", r"\bmadarchod\b", r"\bsaala\b", r"\bkutte\b",
                      r"\bbhenchod\b", r"\bkaminey\b", r"\bbhen ki aankh\b", r"\bchaman\b", r"\bmaa ki\b",
                      r"\bsuar\b", r"\blauda\b", r"\bhaggu\b", r"\bkutta\b", r"\bkutti\b",r"\bdumb\b",r"\bbitch\b"
                      r"\bmadharchod\b", r"\bmaaki\b", r"\bmaakichut\b", r"\bmaakibhosdik\xe2\x80\x8b",
                      r"\bfuck off\b", r"\basshole\b", r"\bbitch\b", r"\bshit\b", r"\bscrew you\b", r"\bgo to hell\b",
                      r"\bass\b", r"\bdamn\b", r"\bdick\b", r"\bcrappy\b", r"\bfool\b", r"\bidiots?\b", r"\bnonsense\b",
                      r"\bpathetic\b", r"\bstupid\b", r"\bsuck\b", r"\bwtf\b", r"\bgtfo\b", r"\bf\*ck\b", r"\bsh\*t\b",
                      r"\bdickhead\b", r"\bmad\b", r"\binsane\b", r"\bbullshit\b", r"\bnonsense\b",
                      r"\basshat\b", r"\bassclown\b", r"\basswipe\b", r"\bbullcrap\b", r"\bclusterfuck\b",
                      r"\bcockhead\b", r"\bcockwaffle\b", r"\bdickwad\b", r"\bdickweed\b", r"\bdouche\b",
                      r"\bdouchecanoe\b", r"\bdouchenozzle\b", r"\bfuckface\b", r"\bfucktard\b", r"\bfuckwit\b",
                      r"\bshithead\b", r"\bshitbag\b", r"\bshit-for-brains\b", r"\bshitstorm\b", r"\btwatwaffle\b",
                      r"\bcocksucker\b", r"\bcumstain\b", r"\bdicksplash\b", r"\bfucknut\b", r"\bjerkoff\b",
                      r"\bknobhead\b", r"\bpisshead\b", r"\bpissflap\b", r"\bpricktease\b", r"\bskank\b",
                      r"\bslag\b", r"\bslapper\b", r"\btosser\b", r"\bwank stain\b", r"\bwanker\b",
                      r"\bwankshaft\b", r"\bwankstain\b", r"\bbastardized\b", r"\bdip shit\b", r"\bshitbird\b",
                      r"\bdick cheese\b", r"\bcockroach\b", r"\bshit-kicking\b", r"\bass-kisser\b", r"\bass-faced\b",
                      r"\bass-fucker\b", r"\bshit-eating\b", r"\bass-wipe\b", r"\bcock-jockey\b", r"\bcock-sucker\b",
                      r"\bass-pirate\b", r"\bcock-master\b", r"\bass-kisser\b", r"\bcock-up\b", r"\bcock-eyed\b",
                      r"\bcockamamie\b", r"\bdickwad\b", r"\bass-backward\b", r"\bshit-kicker\b", r"\bass-monkey\b",
                      r"\bass over teakettle\b", r"\bass-backwards\b", r"\bshit-for-brains\b", r"\bshit-wit\b",
                      r"\bass-licking\b", r"\bcock-a-doodle-do\b", r"\bcock and bull\b", r"\bcock and balls\b",
                      r"\bcock and cow\b", r"\bass-covering\b", r"\bcock a snook\b", r"\bcock of the walk\b",
                      r"\bcock-a-hoop\b", r"\bcock and mammy\b", r"\bcock-and-bull\b", r"\bassess\b", r"\basshole\b",
                      r"\bchutiya\b", r"\bgandu\b", r"\bmc\b", r"\bmadarchod\b", r"\bbhosdike\b",
                      r"\bteri maa ki\b", r"\bteri behen ki\b", r"\blund\b", r"\bchut\b", r"\bchutiyapa\b",
                      r"\bgaand\b", r"\bsaala\b", r"\bmaa ki aankh\b", r"\bmaa ki\b", r"\bbehenchod\b",
                      r"\bkutte\b", r"\bkamine\b", r"\bharami\b", r"\bchootiya\b", r"\bchutiye\b",
                      r"\bchutiyagiri\b", r"\bgaandu\b", r"\bmc\b", r"\bmadar\b", r"\bmaa ki\b",
                      r"\bchodu\b", r"\bchod\b", r"\blavde\b", r"\bghasti\b", r"\bjaat\b",
                      r"\bsuvar\b", r"\blauda\b", r"\bloda\b", r"\blodi\b", r"\bmakichut\b",
                      r"\bghanta\b", r"\bchamar\b", r"\bhaggu\b", r"\bkuttiya\b", r"\bkutte\b",
                      r"\bmakichut\b", r"\bmal\b", r"\bteri maa ka\b", r"\bteri behen ka\b", r"\bteri maa ki chut\b",
                      r"\bteri behen ki chut\b", r"\bteri maa ka bhosda\b", r"\bteri behen ka bhosda\b", r"\bteri maa ka bhosda\b", r"\bteri behen ka bhosda\b",
                      r"\bmadharchod\b", r"\bmaaki\b", r"\bmaakichut\b", r"\bmaakibhosdik\xe2\x80\x8b",
                      r"\bthirudan\b", r"\bmoodhevi\b", r"\bootha\b", r"\bpotha\b", r"\btholla\b",
                      r"\bpunda\b", r"\bthayoli\b", r"\bthirudargal\b", r"\bthollaikatchigal\b", r"\bsaavu\b",
                      r"\bmuruda\b", r"\bsaavul\b", r"\bthayirsaadham\b", r"\bsaapadu\b", r"\bvayiru\b",
                      r"\bvayiruthala\b", r"\bsaadu\b", r"\bthollaikatchi\b", r"\bpoosaari\b", r"\bmodhalaali\b",
                      r"\bthaaiyoli\b", r"\bpoyachudi\b", r"\bchithi\b", r"\bthollaikkatchi\b", r"\bthangamaari\b",
                      r"\bthullu\b", r"\btharuthala\b", r"\bvayasupal\b", r"\bmulaiyadi\b", r"\bmaravadi\b",
                      r"\bthayir sadham\b", r"\bvayira\b", r"\bmaami\b", r"\bthirudan paravai\b", r"\bthollai katchi\b",
                      r"\bsaapad\b", r"\bchithi\b", r"\bthirudargal\b", r"\bvayasupall\b", r"\bthooki\b",
                      r"\bthimberch\b", r"\btomberbhal\b", r"\bmoodevi\b", r"\bthirudargal\b", r"\bvayasupall\b",
                      r"\bmoonji\b", r"\bthiruppi\b", r"\bthuppin\b", r"\bthavuthu\b", r"\bpathuthru\b",
                      r"\bsurundi\b", r"\botha\b", r"\bthevadiya\b", r"\btholavaichu\b", r"\bthaiyolvi\b",
                      r"\bsaavula\b", r"\bthevadiya\b", r"\bthevadiyam\b", r"\btholi\b", r"\bthola\b",
                      r"\btholla\b", r"\btholavi\b", r"\bthalavaikindra\b", r"\bthairvu\b", r"\bthevadiya\b",
                      r"\bthooki\b", r"\btholudan\b", r"\btholachi\b", r"\bthukki\b", r"\btholvi\b"
                   ]
